community_bridge: PROJECT-NAME
github: [denvernine, USERNAME, USERNAME, USERNAME]
issuehunt: USERNAME
ko_fi: USERNAME
liberapay: USERNAME
open_collective: USERNAME
otechie: USERNAME
patreon: USERNAME
tidelift: PLATFORM-NAME/PACKAGE-NAME
custom: [LINK1, LINK2, LINK3, LINK4]
